USE SANDBOX
GO

-- TABLE CREATION
CREATE TABLE SEC_USER_TOKEN(
	TOK_ID		INT IDENTITY(1,1)		NOT NULL PRIMARY KEY,
	TOK_USER	VARCHAR(50)				NOT NULL,
	TOK_KEY		VARCHAR(50)				NOT NULL,
	TOK_ATIVO	CHAR(1)					NOT NULL CHECK(TOK_ATIVO IN('S', 'N'))
);